#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       ksh, or zsh, then change the shebang line to whatever that shell is.
#   (2) This script should be executable by a user called 'gradle' and should be placed in
#       the standard location as per the Gradle documentation at
#       https://docs.gradle.org/current/userguide/gradle_wrapper.html
#
#   You can find Gradle at https://gradle.org
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}    # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]                          # test whether app_path is a symlink
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}    # drop leading whitespace+qualifier and everything up to last ' -> '
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != unlimited.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NOPAUSE* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/$APP_JAR


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAR_PATH="$JAVA_HOME/bin/java"
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAR_PATH=java
fi

# Increase the maximum file descriptors if we can.
if [ "$darwin" = "true" -a ! -wrl "$HOME/.profile" ] && [ -f "$HOME/.profile" ] ; then
    sed -i '' '/.*JAVA_OPTS/d' "$HOME/.profile"
    sed -i '' '/.*CLASSPATH/d' "$HOME/.profile"
    echo "export JAVA_TOOL_OPTIONS=\"\$JAVA_TOOL_OPTIONS -Dfile.encoding=UTF-8\"" >>"$HOME/.profile"
fi

exec "$JAR_PATH" \
  -Xmx64m \
  -Xms64m \
  -cp "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
